server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://192.168.2.28:3306/hxp_edition2_develop?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.jdbc.Driver
    username: masterMind
    password: Sino+masterMind

  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html


mybatis:
  type-aliases-package: com.cn.model
  config-locations: classpath:mybatis/confg.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

